Project/Opa21_A_Csharp_Assignment/Pages/StudentInfo/ClassEnroll.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Opa21_A_Csharp_Assignment.Model;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Opa21_A_Csharp_Assignment.Pages.Utility;

namespace Opa21_A_Csharp_Assignment.Pages.StudentInfo
{
    [Authorize(Roles = StaticDetail.StudentUser)]
    public class ClassEnrollModel : PageModel
    {

        private DatabaseContext databaseContext;
        private readonly UserManager<IdentityUser> _userManager;

        public ClassEnrollModel(DatabaseContext _databaseContext, UserManager<IdentityUser> userManager)
        {
            this.databaseContext = _databaseContext;
            _userManager = userManager;
        }

        public List<Course> courseList { get; set; }
        public User studentUser { get; set; }
        public List<Course> notEnrolledCourses { get; set; }
        public List<Enrollment> enrollments { get; set; }
        public int studentId { get; set; }
        public Student student { get; set; }
        public Course course { get; set; }

        public async Task OnGet()
        {
            notEnrolledCourses = new List<Course>();
            var id = _userManager.GetUserId(HttpContext.User);
            studentUser = (User)(await databaseContext.Users.FindAsync(id));
            studentId = studentUser.StudentId;
            courseList = await databaseContext.Course.ToListAsync();
            enrollments = await databaseContext.Enrollment.Where(x => x.Student.StudentId == studentId).ToListAsync();


            bool inList = false;
            for (int i = 0; i < courseList.Count; i++)
            {
                inList = false;

                foreach (var enrolledClass in enrollments)
                {
                    if (courseList[i].CourseId == enrolledClass.Course.CourseId)
                    {
                        inList = true;
                    }
                }

                if (!inList)
                {
                    notEnrolledCourses.Add(courseList[i]);
                }
            }
        }

        public async Task<IActionResult> OnPostEnroll(int id)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(HttpContext.User);
                studentUser = (User)(await databaseContext.Users.FindAsync(userId));
                studentId = studentUser.StudentId;
                course = await databaseContext.Course.FindAsync(id);
                student = await databaseContext.Student.FindAsync(studentId);
                Enrollment en = new Enrollment { Course = course, Student = student };
                await databaseContext.Enrollment.AddAsync(en);
                await databaseContext.SaveChangesAsync();
               return RedirectToPage("/StudentInfo/StudentPage");
            }
            return Page();
        }


    }
}

Project/Opa21_A_Csharp_Assignment/Pages/StudentInfo/StudentPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Opa21_A_Csharp_Assignment.Model;
using Opa21_A_Csharp_Assignment.Pages.Utility;

namespace Opa21_A_Csharp_Assignment.Pages.StudentInfo
{
    [Authorize(Roles = StaticDetail.StudentUser)]
    public class StudentPageModel : PageModel
    {

        private DatabaseContext databaseContext;
        private readonly UserManager<IdentityUser> _userManager;
        public StudentPageModel(DatabaseContext _databaseContext, UserManager<IdentityUser> userManager)
        {
            this.databaseContext = _databaseContext;
            _userManager = userManager;
        }

        public List<Course> courseList { get; set; }
        public List<Enrollment> enrollments { get; set; }
        public List<Student> studentList { get; set; }
        public List<Course> studentCourseList { get; set; }
        public User studentUser { get; set; }
        public int studentId { get; set; }
        public Student student { get; set; }
        public Course course { get; set; }
        public async Task OnGet()
        {
            var id = _userManager.GetUserId(HttpContext.User);
            studentUser = (User)(await databaseContext.Users.FindAsync(id));
            studentId = studentUser.StudentId;
            studentCourseList = new List<Course>();
            studentList = await databaseContext.Student.ToListAsync();
            courseList = await databaseContext.Course.ToListAsync();
            enrollments = await databaseContext.Enrollment.Where(x => x.Student.StudentId == studentId).ToListAsync();
            foreach (var course in enrollments)
            {
                studentCourseList.Add(course.Course);
            }
        }

        public async Task<IActionResult> OnPostQuit(int id)
        {
            if (ModelState.IsValid)
            {
                courseList = await databaseContext.Course.ToListAsync();
                studentList = await databaseContext.Student.ToListAsync();
                var userId = _userManager.GetUserId(HttpContext.User);
                studentUser = (User)(await databaseContext.Users.FindAsync(userId));
                studentId = studentUser.StudentId;
                List<Enrollment> allEnrollments = await databaseContext.Enrollment.ToListAsync();
                Enrollment enrollmentItem = null;
                foreach (var enrollment in allEnrollments)
                {
                    if(enrollment.Student.StudentId == studentId && enrollment.Course.CourseId == id)
                    {
                        enrollmentItem = enrollment;
                    }
                }
                if(enrollmentItem != null)
                {
                    databaseContext.Enrollment.Remove(enrollmentItem);
                    await databaseContext.SaveChangesAsync();
                }
                return RedirectToPage("/StudentInfo/StudentPage");
            }
            return Page();
        }
    }
}

Project/Opa21_A_Csharp_Assignment/Pages/StudentInfo/ClassEnroll.cshtml
@page
@model Opa21_A_Csharp_Assignment.Pages.StudentInfo.ClassEnrollModel
@{
}


<h2>Enroll in a new class</h2>


<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">
                <label asp-for="notEnrolledCourses.FirstOrDefault().Name"></label>
            </th>
            <th scope="col">
                <label asp-for="notEnrolledCourses.FirstOrDefault().Location"></label>
            </th>
            <th scope="col">
                <label></label>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var course in Model.notEnrolledCourses)
        {
            <tr>
                <td>
                    @Html.DisplayFor(variable => course.Name)
                </td>
                <td>
                    @Html.DisplayFor(variable => course.Location)
                </td>
                <form method="post">
                <td>
                    <button class="btn btn-success" asp-page-handler="Enroll" asp-route-id="@course.CourseId">Enroll</button>
                </td>
                </form>

            </tr>
        }
    </tbody>
</table>

Project/Opa21_A_Csharp_Assignment/Pages/StudentInfo/StudentPage.cshtml
@page
@model Opa21_A_Csharp_Assignment.Pages.StudentInfo.StudentPageModel
@{
}



<p> All your enrolled classes</p>


<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">
                <label>Class Name</label>
            </th>
            <th scope="col">
                <label>Class Location</label>
            </th>
            <th scope="col">
                <label>Teacher Name</label>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var course in Model.studentCourseList)
        {
        <tr>
            <td>
                @Html.DisplayFor(variable => course.Name)
            </td>
            <td>
                @Html.DisplayFor(variable => course.Location)
            </td>
            <form method="post">
                <td>
                    <button class="btn btn-danger" asp-page-handler="Quit" asp-route-id="@course.CourseId">Quit Course</button>
                </td>
            </form>
        </tr>
        }
    </tbody>
</table>