Project/Opa21_A_Csharp_Assignment/Pages/AdminPages/AddPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Opa21_A_Csharp_Assignment.Model;
using Opa21_A_Csharp_Assignment.Pages.Utility;

namespace Opa21_A_Csharp_Assignment.Pages.AdminPages
{
    [Authorize(Roles = StaticDetail.AdminUser)]
    public class AddPageModel : PageModel
    {

        private DatabaseContext databaseContext;

        public AddPageModel(DatabaseContext _databaseContext)
        {
            this.databaseContext = _databaseContext;
        }

        [BindProperty]
        public Course Course { get; set; }

        public async Task OnGet(string? type)
        {
           
        }

        public async Task<IActionResult> OnPostAddCourse()
        {
            if (ModelState.IsValid)
            {
                await databaseContext.AddAsync(Course);
                await databaseContext.SaveChangesAsync();
                return RedirectToPage("/AdminPages/EditCourses");
            }
            return Page();
        }
    }
}

Project/Opa21_A_Csharp_Assignment/Pages/AdminPages/EditCourses.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Opa21_A_Csharp_Assignment.Model;
using Opa21_A_Csharp_Assignment.Pages.Utility;

namespace Opa21_A_Csharp_Assignment.Pages.AdminPages
{
    [Authorize(Roles = StaticDetail.AdminUser)]
    public class EditCoursesModel : PageModel
    {
        private DatabaseContext databaseContext;
        public EditCoursesModel(DatabaseContext _databaseContext)
        {
            this.databaseContext = _databaseContext;
        }

        public List<Course> courseList { get; set; }
        public List<Enrollment> enrollmentList { get; set; }
        public List<TeacherEnrollment> teacherEnrollmentList { get; set; }
        public async Task OnGet()
        {
            courseList = await databaseContext.Course.ToListAsync();
        }

        public async Task<IActionResult> OnPostDelete(int id)
        {
            Course course = await databaseContext.Course.FindAsync(id);

            if(course == null)
            {
                return NotFound();
            }
            enrollmentList = await databaseContext.Enrollment.Where(x => x.Course.CourseId == id).ToListAsync();
            foreach (var enrollment in enrollmentList)
            {
                databaseContext.Enrollment.Remove(enrollment);
                await databaseContext.SaveChangesAsync();
            }
            teacherEnrollmentList = await databaseContext.TeacherEnrollment.Where(x => x.Course.CourseId == id).ToListAsync();
            foreach (var teacherEnrollment in teacherEnrollmentList)
            {
                databaseContext.TeacherEnrollment.Remove(teacherEnrollment);
                await databaseContext.SaveChangesAsync();
            }
            databaseContext.Course.Remove(course);
            await databaseContext.SaveChangesAsync();

            return RedirectToPage("/AdminPages/EditCourses");
        }
    }
}

Project/Opa21_A_Csharp_Assignment/Pages/AdminPages/EditPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Opa21_A_Csharp_Assignment.Model;
using Opa21_A_Csharp_Assignment.Pages.Utility;

namespace Opa21_A_Csharp_Assignment.Pages.AdminPages
{
    [Authorize(Roles = StaticDetail.AdminUser)]
    public class EditPageModel : PageModel
    {
        private DatabaseContext databaseContext;

        public EditPageModel(DatabaseContext _databaseContext)
        {
            this.databaseContext = _databaseContext;
        }

 
        [BindProperty]
        public Course course { get; set; }

        public async Task OnGet(int id)
        {
            course = await databaseContext.Course.FindAsync(id);
        }
        
        public async Task<IActionResult> OnPostEditCourse()
        {
            if (ModelState.IsValid)
            {
                databaseContext.Course.Update(course);
                await databaseContext.SaveChangesAsync();
                return RedirectToPage("/AdminPages/EditCourses");
            }
            return Page();
        }
    }
}

Project/Opa21_A_Csharp_Assignment/Pages/AdminPages/AddPage.cshtml
@page
@model Opa21_A_Csharp_Assignment.Pages.AdminPages.AddPageModel
@{
}




<h2>Add a new course</h2>

<form method="post">
    <div>
        <label asp-for="Course.Name"></label>
        <input asp-for="Course.Name" placeholder="ex. Math 101" />
    </div>
    <div>
        <label asp-for="Course.Location"></label>
        <input asp-for="Course.Location" placeholder="ex. A101" />
    </div>
    <input type="submit" value="submit" asp-page-handler="AddCourse" />
</form>

<div>
    <a href="/AdminPages/EditCourses">Go back</a>
</div>

Project/Opa21_A_Csharp_Assignment/Pages/AdminPages/EditCourses.cshtml
@page
@model Opa21_A_Csharp_Assignment.Pages.AdminPages.EditCoursesModel
@{
}


<h2>Add, Edit and Delete courses</h2>


<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">
                <label asp-for="courseList.FirstOrDefault().Name"></label>
            </th>
            <th scope="col">
                <label asp-for="courseList.FirstOrDefault().Location"></label>
            </th>
            <th scope="col">
                <label></label>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var course in Model.courseList)
        {
        <tr>
            <td>
                @Html.DisplayFor(variable => course.Name)
            </td>
            <td>
                @Html.DisplayFor(variable => course.Location)
            </td>
            <td>
                <a asp-route-id="@course.CourseId" asp-page="/AdminPages/Editpage">Edit Course</a>
            </td>
            <form method="post">
            <td>
                <button class="btn btn-danger" asp-page-handler="Delete" asp-route-id="@course.CourseId" onclick="return confirm('are you sure?')">Delete</button>
            </td>
            </form>

        </tr>
        }
        <tr>
            <td>
                <a asp-route-type="admin" asp-page="/AdminPages/AddPage">Add New Course</a>
            </td>
            
        </tr>
    </tbody>
</table>

Project/Opa21_A_Csharp_Assignment/Pages/AdminPages/EditPage.cshtml
@page
@model Opa21_A_Csharp_Assignment.Pages.AdminPages.EditPageModel
@{
}








    <h2>Edit course</h2>

    <form method="post">
        <input type="hidden" asp-for="course.CourseId" />
        <div asp-validation-summary="ModelOnly" ></div>
        <div>
            <label asp-for="course.Name"></label>
            <input asp-for="course.Name" placeholder="ex. Math 101" />
        </div>
        <div>
            <label asp-for="course.Location"></label>
            <input asp-for="course.Location" placeholder="ex. A101" />
        </div>
        <input type="submit" value="submit" asp-page-handler="EditCourse" />
    </form>

    <div>
        <a href="/AdminPages/EditCourses">Go back</a>
    </div>