Project/Opa21_A_Csharp_Assignment/Pages/TeacherPages/TeacherClasses.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Opa21_A_Csharp_Assignment.Model;
using Opa21_A_Csharp_Assignment.Pages.Utility;

namespace Opa21_A_Csharp_Assignment.Pages.TeacherPages
{
    [Authorize(Roles = StaticDetail.TeacherUser)]
    public class TeacherClassesModel : PageModel
    {
        private DatabaseContext databaseContext;
        private readonly UserManager<IdentityUser> _userManager;

        public TeacherClassesModel(DatabaseContext _databaseContext, UserManager<IdentityUser> userManager)
        {
            this.databaseContext = _databaseContext;
            _userManager = userManager;
        }

        public List<Course> courseList { get; set; }
        public User teacherUser { get; set; }
        public List<Course> notTeachingCourses { get; set; }
        public List<TeacherEnrollment> teacherEnrollments { get; set; }
        public int teacherId { get; set; }
        public Teacher teacher { get; set; }
        public Course course { get; set; }

        public async Task OnGet()
        {
            notTeachingCourses = new List<Course>();
            var id = _userManager.GetUserId(HttpContext.User);
            teacherUser = (User)(await databaseContext.Users.FindAsync(id));
            teacherId = teacherUser.TeacherId;
            courseList = await databaseContext.Course.ToListAsync();
            teacherEnrollments = await databaseContext.TeacherEnrollment.Where(x => x.Teacher.TeacherId == teacherId).ToListAsync();


            bool inList = false;
            for (int i = 0; i < courseList.Count; i++)
            {
                inList = false;

                foreach (var enrolledClass in teacherEnrollments)
                {
                    if (courseList[i].CourseId == enrolledClass.Course.CourseId)
                    {
                        inList = true;
                    }
                }

                if (!inList)
                {
                    notTeachingCourses.Add(courseList[i]);
                }
            }
        }

        public async Task<IActionResult> OnPostTeach(int id)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(HttpContext.User);
                teacherUser = (User)(await databaseContext.Users.FindAsync(userId));
                teacherId = teacherUser.TeacherId;
                course = await databaseContext.Course.FindAsync(id);
                teacher = await databaseContext.Teacher.FindAsync(teacherId);
                TeacherEnrollment en = new TeacherEnrollment { Course = course, Teacher = teacher };
                await databaseContext.TeacherEnrollment.AddAsync(en);
                await databaseContext.SaveChangesAsync();
                return RedirectToPage("/TeacherPages/TeacherClasses");
            }
            return Page();
        }
    }
}

Project/Opa21_A_Csharp_Assignment/Pages/TeacherPages/TeacherPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Opa21_A_Csharp_Assignment.Model;
using Opa21_A_Csharp_Assignment.Pages.Utility;

namespace Opa21_A_Csharp_Assignment.Pages.TeacherPages
{
    [Authorize(Roles = StaticDetail.TeacherUser)]
    public class TeacherPageModel : PageModel
    {
        private DatabaseContext databaseContext;
        private readonly UserManager<IdentityUser> _userManager;
        public TeacherPageModel(DatabaseContext _databaseContext, UserManager<IdentityUser> userManager)
        {
            this.databaseContext = _databaseContext;
            _userManager = userManager;
        }

        public List<Course> courseList { get; set; }
        public List<TeacherEnrollment> teacherEnrollments { get; set; }
        public List<Student> studentList { get; set; }
        public List<Teacher> teacherList { get; set; }
        public List<Course> teacherCourseList { get; set; }
        public User teacherUser { get; set; }
        public int teacherId { get; set; }
        public Teacher teacher { get; set; }
        public Course course { get; set; }
        public async Task OnGet()
        {
            var id = _userManager.GetUserId(HttpContext.User);
            teacherUser = (User)(await databaseContext.Users.FindAsync(id));
            teacherId = teacherUser.TeacherId;
            teacherCourseList = new List<Course>();
            //studentList = await databaseContext.Teacher.ToListAsync();
            courseList = await databaseContext.Course.ToListAsync();
            teacherEnrollments = await databaseContext.TeacherEnrollment.Where(x => x.Teacher.TeacherId == teacherId).ToListAsync();
            foreach (var course in teacherEnrollments)
            {
                teacherCourseList.Add(course.Course);
            }
        }

        public async Task<IActionResult> OnPostQuit(int id)
        {
            if (ModelState.IsValid)
            {
                courseList = await databaseContext.Course.ToListAsync();
                studentList = await databaseContext.Student.ToListAsync();
                teacherList = await databaseContext.Teacher.ToListAsync();
                var userId = _userManager.GetUserId(HttpContext.User);
                teacherUser = (User)(await databaseContext.Users.FindAsync(userId));
                teacherId = teacherUser.TeacherId;
                List<TeacherEnrollment> allEnrollments = await databaseContext.TeacherEnrollment.ToListAsync();
                TeacherEnrollment enrollmentItem = null;
                foreach (var enrollment in allEnrollments)
                {
                    if (enrollment.Teacher.TeacherId == teacherId && enrollment.Course.CourseId == id)
                    {
                        enrollmentItem = enrollment;
                    }
                }
                if (enrollmentItem != null)
                {
                    databaseContext.TeacherEnrollment.Remove(enrollmentItem);
                    await databaseContext.SaveChangesAsync();
                }
                return RedirectToPage("/TeacherPages/TeacherPage");
            }
            return Page();
        }
    }
}

Project/Opa21_A_Csharp_Assignment/Pages/TeacherPages/TeacherClasses.cshtml
@page
@model Opa21_A_Csharp_Assignment.Pages.TeacherPages.TeacherClassesModel
@{
}


<h2>Pick a class to teach</h2>


<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">
                <label asp-for="notTeachingCourses.FirstOrDefault().Name"></label>
            </th>
            <th scope="col">
                <label asp-for="notTeachingCourses.FirstOrDefault().Location"></label>
            </th>
            <th scope="col">
                <label></label>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var course in Model.notTeachingCourses)
        {
            <tr>
                <td>
                    @Html.DisplayFor(variable => course.Name)
                </td>
                <td>
                    @Html.DisplayFor(variable => course.Location)
                </td>
                <form method="post">
                <td>
                    <button class="btn btn-success" asp-page-handler="Teach" asp-route-id="@course.CourseId">Teach class</button>
                </td>
                </form>

            </tr>
        }
    </tbody>
</table>

Project/Opa21_A_Csharp_Assignment/Pages/TeacherPages/TeacherPage.cshtml
@page
@model Opa21_A_Csharp_Assignment.Pages.TeacherPages.TeacherPageModel
@{
}


<p> All classes where logged in teacher is teaching</p>


<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">
                <label>Class Name</label>
            </th>
            <th scope="col">
                <label>Class Location</label>
            </th>
            <th scope="col">
                <label>Teacher Name</label>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var course in Model.teacherCourseList)
        {
            <tr>
                <td>
                    @Html.DisplayFor(variable => course.Name)
                </td>
                <td>
                    @Html.DisplayFor(variable => course.Location)
                </td>
                <form method="post">
                <td>
                    <button class="btn btn-danger" asp-page-handler="Quit" asp-route-id="@course.CourseId">Quit Course</button>
                </td>
                </form>
            </tr>
        }
    </tbody>
</table>